server:
    port: 10001
spring:
    datasource:
        url: jdbc:mysql:///data-change?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
stars:
    dictionary:
        table-name: stars_dictionary
        field-code: stars_code
        field-id: stars_id
        field-name: stars_name
        field-value: stars_value
        field-parent-id: parent_id
    config:
        # 自定义 智能映射匹配
        mapping-suffix: Text, Str, Ext, Custom
mybatis:
    mapper-locations: classpath:mapper/*.xml

default:
    file:
        path: E:\DataCache\test\
        ffmpeg-path: D:\Java\ffmpeg\bin/ffmpeg.exe