server:
    port: 10000
spring:
    datasource:
        url: jdbc:mysql:///data-change?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: Zhou$123456!
        driverClassName: com.mysql.cj.jdbc.Driver
stars:
    dictionary:
        table-name: stars_dictionary
        field-code: stars_code
        field-id: stars_id
        field-name: stars_name
        field-value: stars_value
        field-parent-id: parent_id
mybatis:
    mapper-locations: classpath:mapper/*.xml